package com.domain;
// Generated Dec 21, 2015 1:36:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="carrepairinvoicing"
)
public class Customer  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="CustomerNo", unique=true, nullable=false)
    private int customerNo;
    @Column(name="LastName", length=45)
    private String lastName;
    @Column(name="FirstName", length=45)
    private String firstName;
    @Column(name="Street", length=45)
    private String street;
    @Column(name="State", length=45)
    private String state;
    @Column(name="City", length=45)
    private String city;
    @Column(name="ContactNo", length=45)
    private String contactNo;
    @Temporal(TemporalType.DATE)
    @Column(name="Birthday", length=10)
    private Date birthday;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

    public Customer() {
    }

	
    public Customer(int customerNo) {
        this.customerNo = customerNo;
    }
    public Customer(int customerNo, String lastName, String firstName, String street, String state, String city, String contactNo, Date birthday, Set<Vehicle> vehicles) {
       this.customerNo = customerNo;
       this.lastName = lastName;
       this.firstName = firstName;
       this.street = street;
       this.state = state;
       this.city = city;
       this.contactNo = contactNo;
       this.birthday = birthday;
       this.vehicles = vehicles;
    }
   
    public int getCustomerNo() {
        return this.customerNo;
    }
    
    public void setCustomerNo(int customerNo) {
        this.customerNo = customerNo;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }
}


