package com.domain;
// Generated Dec 21, 2015 1:36:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Invoicedetail generated by hbm2java
 */
@Entity
@Table(name="invoicedetail"
    ,catalog="carrepairinvoicing"
)
public class Invoicedetail  implements java.io.Serializable {

    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="invoiceNo", column=@Column(name="InvoiceNo", nullable=false) ), 
        @AttributeOverride(name="seriesNo", column=@Column(name="SeriesNo", nullable=false) ) } )
    private InvoicedetailId id;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="InvoiceNo", nullable=false, insertable=false, updatable=false)
    private Invoice invoice;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PartJobNo", nullable=false)
    private Labpartssuppmisc labpartssuppmisc;
    @Column(name="Qty", nullable=false)
    private int qty;
    @Column(name="UnitPrice", precision=10, scale=5)    
    private BigDecimal unitPrice;
    @Column(name="Amount", nullable=false, precision=10, scale=5)
    private BigDecimal amount;

    public Invoicedetail() {
    }

	
    public Invoicedetail(InvoicedetailId id, Invoice invoice, Labpartssuppmisc labpartssuppmisc, int qty, BigDecimal amount) {
        this.id = id;
        this.invoice = invoice;
        this.labpartssuppmisc = labpartssuppmisc;
        this.qty = qty;
        this.amount = amount;
    }
    public Invoicedetail(InvoicedetailId id, Invoice invoice, Labpartssuppmisc labpartssuppmisc, int qty, BigDecimal unitPrice, BigDecimal amount) {
       this.id = id;
       this.invoice = invoice;
       this.labpartssuppmisc = labpartssuppmisc;
       this.qty = qty;
       this.unitPrice = unitPrice;
       this.amount = amount;
    }
   
    public InvoicedetailId getId() {
        return this.id;
    }
    
    public void setId(InvoicedetailId id) {
        this.id = id;
    }

    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    public Labpartssuppmisc getLabpartssuppmisc() {
        return this.labpartssuppmisc;
    }
    
    public void setLabpartssuppmisc(Labpartssuppmisc labpartssuppmisc) {
        this.labpartssuppmisc = labpartssuppmisc;
    }

    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}


