package com.domain;
// Generated Dec 21, 2015 1:36:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="invoice"
    ,catalog="carrepairinvoicing"
)
public class Invoice  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idInvoice", unique=true, nullable=false)
    private int idInvoice;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VehicleNo")
    private Vehicle vehicle;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateTimePromise", nullable=false, length=19)
    private Date dateTimePromise;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TimeReceived", length=19)
    private Date timeReceived;
    @Column(name="TotatAmount", precision=10, scale=5)
    private BigDecimal totatAmount;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="invoice")
    private Set<Invoicedetail> invoicedetails = new HashSet<Invoicedetail>(0);

    public Invoice() {
    }

	
    public Invoice(int idInvoice, Date dateTimePromise) {
        this.idInvoice = idInvoice;
        this.dateTimePromise = dateTimePromise;
    }
    public Invoice(int idInvoice, Vehicle vehicle, Date dateTimePromise, Date timeReceived, BigDecimal totatAmount, Set<Invoicedetail> invoicedetails) {
       this.idInvoice = idInvoice;
       this.vehicle = vehicle;
       this.dateTimePromise = dateTimePromise;
       this.timeReceived = timeReceived;
       this.totatAmount = totatAmount;
       this.invoicedetails = invoicedetails;
    }
   
    public int getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(int idInvoice) {
        this.idInvoice = idInvoice;
    }

    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    public Date getDateTimePromise() {
        return this.dateTimePromise;
    }
    
    public void setDateTimePromise(Date dateTimePromise) {
        this.dateTimePromise = dateTimePromise;
    }


    public Date getTimeReceived() {
        return this.timeReceived;
    }
    
    public void setTimeReceived(Date timeReceived) {
        this.timeReceived = timeReceived;
    }

    public BigDecimal getTotatAmount() {
        return this.totatAmount;
    }
    
    public void setTotatAmount(BigDecimal totatAmount) {
        this.totatAmount = totatAmount;
    }

    public Set<Invoicedetail> getInvoicedetails() {
        return this.invoicedetails;
    }
    
    public void setInvoicedetails(Set<Invoicedetail> invoicedetails) {
        this.invoicedetails = invoicedetails;
    }
}


