package com.domain;
// Generated Dec 21, 2015 1:36:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoicedetailId generated by hbm2java
 */
@Embeddable
public class InvoicedetailId  implements java.io.Serializable {

    @Column(name="InvoiceNo", nullable=false)
    private int invoiceNo;
    @Column(name="SeriesNo", nullable=false)
    private int seriesNo;

    public InvoicedetailId() {
    }

    public InvoicedetailId(int invoiceNo, int seriesNo) {
       this.invoiceNo = invoiceNo;
       this.seriesNo = seriesNo;
    }
   
    public int getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(int invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    public int getSeriesNo() {
        return this.seriesNo;
    }
    
    public void setSeriesNo(int seriesNo) {
        this.seriesNo = seriesNo;
    }


   public boolean equals(Object other) {
        if ( (this == other ) ) return true;
                if ( (other == null ) ) return false;
                if ( !(other instanceof InvoicedetailId) ) return false;
                InvoicedetailId castOther = ( InvoicedetailId ) other; 

                return (this.getInvoiceNo()==castOther.getInvoiceNo())
                   && (this.getSeriesNo()==castOther.getSeriesNo());
   }
   
   public int hashCode() {
        int result = 17;

        result = 37 * result + this.getInvoiceNo();
        result = 37 * result + this.getSeriesNo();
        return result;
   }   

}