package com.domain;
// Generated Dec 21, 2015 1:36:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Labpartssuppmisc generated by hbm2java
 */
@Entity
@Table(name="labpartssuppmisc"
    ,catalog="carrepairinvoicing"
)
public class Labpartssuppmisc  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="idPart", unique=true, nullable=false)
    private Integer idPart;
    @Column(name="Name", length=45)
    private String name;
    @Column(name="Desc", length=500)
    private String desc;
    @Column(name="UnitPrice", precision=10, scale=5)
    private BigDecimal unitPrice;
    @Column(name="Category", length=45)
    private String category;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="labpartssuppmisc")
    private Set<Invoicedetail> invoicedetails = new HashSet<Invoicedetail>(0);

    public Labpartssuppmisc() {
    }

    public Labpartssuppmisc(String name, String desc, BigDecimal unitPrice, String category, Set<Invoicedetail> invoicedetails) {
       this.name = name;
       this.desc = desc;
       this.unitPrice = unitPrice;
       this.category = category;
       this.invoicedetails = invoicedetails;
    }
   
    public Integer getIdPart() {
        return this.idPart;
    }
    
    public void setIdPart(Integer idPart) {
        this.idPart = idPart;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }

    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    public Set<Invoicedetail> getInvoicedetails() {
        return this.invoicedetails;
    }
    
    public void setInvoicedetails(Set<Invoicedetail> invoicedetails) {
        this.invoicedetails = invoicedetails;
    }
}


