/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mechanic;

import com.mechanic.Customer.CustomerList;
import com.service.CustomerService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author 201244055
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private final ApplicationContext context;
    private final CustomerService customerService;
        
    
    private CustomerList cl;
    private boolean hasCustomerForm = false;
    
    public GUI(ApplicationContext context) {
        this.context = context;
        this.customerService = (CustomerService) context.getBean("customerService");
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buttonCustomer = new javax.swing.JButton();
        buttonJobsParts = new javax.swing.JButton();
        buttonInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        buttonCustomer.setText("  Customers  ");
        buttonCustomer.setFocusable(false);
        buttonCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCustomerClicked(evt);
            }
        });
        jToolBar1.add(buttonCustomer);

        buttonJobsParts.setText("  Jobs Parts Supplies  ");
        buttonJobsParts.setFocusable(false);
        buttonJobsParts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonJobsParts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonJobsParts);

        buttonInvoice.setText("Invoice");
        buttonInvoice.setFocusable(false);
        buttonInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonInvoice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonInvoice);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustomerClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCustomerClicked
        // TODO add your handling code here:
        if(hasCustomerForm) {
            this.cl.setVisible(true);
        }
        else{
            this.cl = new CustomerList(true, this.context, this.customerService);
            this.cl.setVisible(true);
            hasCustomerForm = true;
        }
    }//GEN-LAST:event_buttonCustomerClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI(new ClassPathXmlApplicationContext("applicationContext.xml")).setVisible(true);
            }
        });
    }
    
    public ApplicationContext getContext(){
        return this.context;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCustomer;
    private javax.swing.JButton buttonInvoice;
    private javax.swing.JButton buttonJobsParts;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
